openapi: "3.0.2"
info:
  version: "1.0"
  title: Welcome to the Tracker API!
  description: This API allows user to get and log their moods.
  contact:
    name: name
servers:
  - url: "http://localhost:5001/api"
    description: Development server
  - url: ""
    description: Production server
paths:
  /api:
    get:
      description: Returns all data
      operationId: get-data
      tags:
        - data
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Mood"
        "401":
          description: Unauthorized
    post:
      description: Log a mood
      operationId: add-data
      tags:
        - data
      security:
        - bearerAuth: []
      parameters:
        - name: mood
          schema:
            type: string
          in: query
          description: The mood to be logged
          required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mood"
        "401":
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Mood:
      type: object
      properties:
        id:
          type: integer
        mood:
          type: string
        date:
          type: string
      required:
        - id
        - mood
        - date
tags:
  - name: data
